### ISSUE TITLE
Support JVM 21

### ISSUE THREAD

**Issue by maxtomin** [google/allocation-instrumenter#55]
Any plans to support Java 21?

Version 3.3.3 fails with:
Unsupported class file major version 65

This would probably require migrating to Asm 9.5

**Comment by writeoncereadmany** [comment]
Is this something we can, even in principle, address via a pull request? Based on https://github.com/google/allocation-instrumenter/pull/41, it appears that the dependency update isn't in this repository, but in a shared repository across all of Google's open-source projects, which implies consequences to potentially many repos.

i do note we're already on asm 9.4 https://github.com/google/bazel-common/blob/master/workspace_defs.bzl, so hopefully it's not a difficult upgrade

**Comment by writeoncereadmany** [comment]
awesome, thanks! any chance we could get a release soon?

**Comment by cpovirk** [comment]
I'll see what I can do. As you can see, the Allocation Instrumenter is not being especially actively developed. I've been hoping to take care of this and https://github.com/google/allocation-instrumenter/pull/54 "eventually," and your comment caught me on a good day for me to at least try :) I have an internal change submitted to bump the bazel-common version, and I'm testing the fix for #54.

**Comment by cpovirk** [comment]
Now released:
- https://github.com/google/allocation-instrumenter/releases/tag/java-allocation-instrumenter-3.3.4
- https://search.maven.org/artifact/com.google.code.java-allocation-instrumenter/java-allocation-instrumenter/3.3.4/jar
