### ISSUE TITLE
Failing while building java-allocation-instrumenter version 3.3.0 using mvn clean install (java-allocation-instrumenter3.3.0)

### ISSUE THREAD

**Issue by shivsrivastava** [google/allocation-instrumenter#57]
Package artifact id: allocation-instrumenter

source code url: https://github.com/google/allocation-instrumenter/tree/java-allocation-instrumenter-3.3.0

Issue Description: Failing while building java-allocation-instrumenter version 3.3.0 using mvn clean install (java-allocation-instrumenter3.3.0)

JDK Version: 1.8

Build CMD: mvn clean install

MVN Version: 3.9.6

gradle version - NA

Error Log: 

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ConstructorInstrumenterTest.testSubclassesAlso:76 Did not see correct number of BasicFunctions expected:<2> but was:<0>
[ERROR] Errors:
[ERROR]   AllocationInstrumenterTest.testTooBig:37 » NullPointer com/google/monitoring/runtime/instrumentation/MuchTooBig.class
[ERROR]   ConstructorInstrumenterTest.testBasicFunctionality:46 » NullPointer
[ERROR]   ConstructorInstrumenterTest.testThreads:28 » NullPointer
[INFO]
[ERROR] Tests run: 7, Failures: 1, Errors: 3, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

attachement: build log attached (jdk 1.8)
[Failed_java_8_logs.txt](https://github.com/google/allocation-instrumenter/files/15143752/Failed_java_8_logs.txt)

OS: windows 10

**Comment by cpovirk** [comment]
Similar to https://github.com/google/guava/issues/7172, we won't go back and change the code at an existing tag. I grant that this one is more embarrassing, since I don't know if these tests worked at all at that tag :\

Unlike in the Guava case, I don't know that there's an easy fix: We subsequently switched the build from Maven to Bazel, so you might have to cherry-pick a whole series of commits in order to get that new build system working :(

**Comment by shivsrivastava** [comment]
Hi @cpovirk , Thanks for update . I was looking for that specific commit from where all test cases are passing. Can you please help me on this?
